export const portfolioData = [
  {
    ticker: "XUU.TO",
    fund_name: "iShares Core S&P U.S. Total Market Index ETF",
    asset_class: "Equity ETF",
    region: "United States",
    current_value: 22000,
    target_weight: 0.25,
    actual_weight: 0.32,
    allocation_drift: 0.07,
    rebalance_amount: -3500,
    suggested_action: "Sell",
  },
  {
    ticker: "VFV.TO",
    fund_name: "Vanguard S&P 500 Index ETF",
    asset_class: "Equity ETF",
    region: "United States",
    current_value: 12500,
    target_weight: 0.15,
    actual_weight: 0.18,
    allocation_drift: 0.03,
    rebalance_amount: -1500,
    suggested_action: "Sell",
  },
  {
    ticker: "VCN.TO",
    fund_name: "Vanguard FTSE Canada All Cap Index ETF",
    asset_class: "Equity ETF",
    region: "Canada",
    current_value: 14500,
    target_weight: 0.3,
    actual_weight: 0.29,
    allocation_drift: -0.01,
    rebalance_amount: 500,
    suggested_action: "Buy",
  },
  {
    ticker: "VAB.TO",
    fund_name: "Vanguard Canadian Aggregate Bond Index ETF",
    asset_class: "Bond ETF",
    region: "Canada",
    current_value: 6500,
    target_weight: 0.15,
    actual_weight: 0.11,
    allocation_drift: -0.04,
    rebalance_amount: 2000,
    suggested_action: "Buy",
  },
  {
    ticker: "CGL.TO",
    fund_name: "iShares Gold Bullion ETF",
    asset_class: "Commodity ETF",
    region: "Global",
    current_value: 3500,
    target_weight: 0.1,
    actual_weight: 0.06,
    allocation_drift: -0.04,
    rebalance_amount: 2000,
    suggested_action: "Buy",
  },
  {
    ticker: "CASH",
    fund_name: "Cash",
    asset_class: "Cash",
    region: "Cash",
    current_value: 1500,
    target_weight: 0.05,
    actual_weight: 0.04,
    allocation_drift: -0.01,
    rebalance_amount: 500,
    suggested_action: "Buy",
  },
]